# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[SSpline]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "3cc3e65b04ff334f4128e6b6d7de3858be5aa89a"
repo-rev = "master"
repo-url = "C:\\Users\\4vektor\\.julia\\dev\\SSpline"
uuid = "2af119c3-c25b-4fc0-9954-fcf9b1025488"
version = "0.1.5"
